🧹 Data Cleaning & Preprocessing

🎯 Objective:
Learn how to clean, preprocess, and prepare data before applying Machine Learning models.

⚠️ Why this matters?
Garbage Data ❌ → Garbage Output ❌
Clean Data ✅ → Better Models ✅

In [ ]:
import pandas as pd
import numpy as np

What is Data Cleaning?
Data Cleaning is the process of:

Fixing incorrect data

Handling missing values

Removing duplicates

Standardizing formats

🔹 Why is Data Preprocessing Important?
Machine Learning models:
Cannot handle missing or messy data properly

Require numerical and consistent input

🔹 Example of Messy Data:

Name	Age	City

Ram	25	Mumbai

Shyam	NaN	mumbai

Ram	25	Mumbai



Problems:
Missing values

Inconsistent text

Duplicate rows

In [ ]:
data = {
    "Name": ["Ram", "Shyam", "Ram", "Sita", None,"Shyam","Shyam","Shyam","Ram"],
    "Age": [25, np.nan, 25, 30, 22,13,17,18,19],
    "City": ["Mumbai", "mumbai", "Mumbai", "Delhi", "Delhi", "Delhi", "Delhi", "Delhi", "Delhi"]
}
print(data)
df = pd.DataFrame(data)
df

{'Name': ['Ram', 'Shyam', 'Ram', 'Sita', None, 'Shyam', 'Shyam', 'Shyam', 'Ram'], 'Age': [25, nan, 25, 30, 22, 13, 17, 18, 19], 'City': ['Mumbai', 'mumbai', 'Mumbai', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi']}

    Name   Age    City
0    Ram  25.0  Mumbai
1  Shyam   NaN  mumbai
2    Ram  25.0  Mumbai
3   Sita  30.0   Delhi
4   None  22.0   Delhi
5  Shyam  13.0   Delhi
6  Shyam  17.0   Delhi
7  Shyam  18.0   Delhi
8    Ram  19.0   Delhi

Common Data Issues
Missing Values → NaN

Duplicate Records

Incorrect Data Types

Inconsistent Text (Mumbai vs mumbai)

We must identify and fix these issues before using data.

In [ ]:
# First few rows
print(df.head())

# Data info
df.info()

# Summary statistics
df.describe()

    Name   Age    City
0    Ram  25.0  Mumbai
1  Shyam   NaN  mumbai
2    Ram  25.0  Mumbai
3   Sita  30.0   Delhi
4   None  22.0   Delhi
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    8 non-null      object
 1   Age     8 non-null      float64
 2   City    9 non-null      object
dtypes: float64(1), object(2)
memory usage: 348.0+ bytes

            Age
count   8.00000
mean   21.12500
std     5.43632
min    13.00000
25%    17.75000
50%    20.50000
75%    25.00000
max    30.00000

## 🔹 Missing Values

Missing values are represented as:
- NaN (Not a Number)
- None

---

## 🔍 Steps:
1. Identify missing values
2. Count them
3. Decide:
   - Drop
   - Fill

In [ ]:
# Check missing values
df.isnull()

# Count missing values
df.isnull().sum()

Name    1
Age     1
City    0
dtype: int64

In [ ]:
# Drop rows with missing values
df_drop = df.dropna()
df_drop

    Name   Age    City
0    Ram  25.0  Mumbai
2    Ram  25.0  Mumbai
3   Sita  30.0   Delhi
5  Shyam  13.0   Delhi
6  Shyam  17.0   Delhi
7  Shyam  18.0   Delhi
8    Ram  19.0   Delhi

## 🔹 Filling Missing Values

### Numerical Columns:
- Mean
- Median

### Categorical Columns:
- Mode

---

## 🧠 When to Use:
- Mean → Normal data
- Median → Skewed data
- Mode → Categories

In [ ]:
# ✅ Best Practice

df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Name"] = df["Name"].fillna(df["Name"].mode()[0])


df

    Name     Age    City
0    Ram  25.000  Mumbai
1  Shyam  21.125  mumbai
2    Ram  25.000  Mumbai
3   Sita  30.000   Delhi
4  Shyam  22.000   Delhi
5  Shyam  13.000   Delhi
6  Shyam  17.000   Delhi
7  Shyam  18.000   Delhi
8    Ram  19.000   Delhi

## 🔹 Selecting Multiple Columns

To work on multiple columns together:

### ✅ Syntax:
df[["col1", "col2"]]

---

## 🔹 Why use this?
- Apply same operation on multiple columns
- Clean multiple columns at once
- Save time and avoid repetition

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Age": [20, np.nan, 25, 30,20],
    "Salary": [20000, 25000, np.nan, 40000,20000],
    "City": ["Nashik", "Delhi", "Pune", "Akola","Mumbai"]
})

df

    Age   Salary    City
0  20.0  20000.0  Nashik
1   NaN  25000.0   Delhi
2  25.0      NaN    Pune
3  30.0  40000.0   Akola
4  20.0  20000.0  Mumbai

In [ ]:
# Fill multiple columns with mean

df[["Age", "Salary"]] = df[["Age", "Salary"]].fillna(df[["Age", "Salary"]].mean())

df

     Age   Salary    City
0  20.00  20000.0  Nashik
1  23.75  25000.0   Delhi
2  25.00  26250.0    Pune
3  30.00  40000.0   Akola
4  20.00  20000.0  Mumbai

In [ ]:
# Convert multiple columns to integer

df[["Age", "Salary"]] = df[["Age", "Salary"]].astype(int)

df.dtypes
df

   Age  Salary    City
0   20   20000  Nashik
1   23   25000   Delhi
2   25   26250    Pune
3   30   40000   Akola
4   20   20000  Mumbai

In [ ]:
# Increase values by 10%

df[["Age", "Salary"]] = df[["Age", "Salary"]].apply(lambda x: x * 1.1)

df

    Age   Salary    City
0  22.0  22000.0  Nashik
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0   Akola
4  22.0  22000.0  Mumbai

In [ ]:
df

    Age   Salary    City
0  22.0  22000.0  Nashik
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0   Akola
4  22.0  22000.0  Mumbai

In [ ]:
df

    Age   Salary    City
0  22.0  22000.0  Nashik
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0   Akola
4  22.0  22000.0    Pune

In [ ]:
# Replace specific values

df[["City"]] = df[["City"]].replace("Mumbai", "Pune")

df

    Age   Salary    City
0  22.0  22000.0  Nashik
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0   Akola
4  22.0  22000.0    Pune

## 🔹 Encoding (Categorical → Numerical)

Machine Learning models only understand numbers.

---

### Types of Data:
1. Nominal → No order (City, Color)
2. Ordinal → Ordered (Low, Medium, High)

---

### Methods:
- One-Hot Encoding
- Label Encoding

In [ ]:
df_encoded = pd.get_dummies(df, columns=["City"])
df_encoded

    Age   Salary  City_Akola  City_Delhi  City_Nashik  City_Pune
0  22.0  22000.0       False       False         True      False
1  25.3  27500.0       False        True        False      False
2  27.5  28875.0       False       False        False       True
3  33.0  44000.0        True       False        False      False
4  22.0  22000.0       False       False        False       True

## 🔹 Label Encoding (Concept)

Converts categories into numbers:

Example:
Mumbai → 0  
Delhi → 1  

⚠️ Not ideal for nominal data (creates fake order)

## 🔹 Duplicate Records

Duplicate data can:
- Bias model
- Reduce accuracy

---

### Solution:
Use drop_duplicates()

In [ ]:
df_no_dup = df.drop_duplicates()
df_no_dup

    Age   Salary    City
0  22.0  22000.0  Nashik
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0   Akola
4  22.0  22000.0    Pune

In [ ]:
# Convert all city names to lowercase
df["City"] = df["City"].str.upper()
df2=df.dropna()
#FEMALE female Female FeMale
df2

    Age   Salary    City
0  22.0  22000.0  NASHIK
1  25.3  27500.0   DELHI
2  27.5  28875.0    PUNE
3  33.0  44000.0   AKOLA
4  22.0  22000.0    PUNE

In [ ]:
df2.dropna()
df2["Age"] = df2["Age"].astype(int)
df2

   Age   Salary    City
0   22  22000.0  NASHIK
1   25  27500.0   DELHI
2   27  28875.0    PUNE
3   33  44000.0   AKOLA
4   22  22000.0    PUNE

# 🌧️ Rainfall Dataset Cleaning

## 🎯 Objective:
Clean and preprocess the dataset `rainfall.csv`

---

## 🔹 Dataset Columns:
- date
- rainfall
- temperature
- humidity
- wind_speed
- weather_condition

---

## ⚠️ Possible Issues:
- Date format not parsed
- Missing values (if any)
- Inconsistent text (Rainy / rainy)
- Wrong data types
- Outliers

---

## ✅ Steps We Will Perform:
1. Load dataset
2. Convert date column
3. Handle missing values
4. Fix text inconsistencies
5. Remove duplicates
6. Detect & handle outliers
7. Final clean dataset

## 📤 Upload CSV File from Local System (Google Colab)

Since the file is on your computer, we need to upload it manually.

---

## 🔹 Steps:
1. Run the cell below
2. Click "Choose Files"
3. Select `rainfall.csv`
4. File will be uploaded to Colab environment

---

After uploading, we can load it using pandas.

In [ ]:
#used another simple method
df =  pd.read_csv('/content/rainfall.csv')

In [ ]:
df.head()

         date  rainfall  temperature  humidity  wind_speed weather_condition
0  2022-01-01      12.5         15.2      78.0         8.5             Rainy
1  2022-01-02       8.2         17.8      65.0         5.2             Rainy
2  2022-01-03       0.0         20.1      52.0         3.1             Sunny
3  2022-01-04       3.7         18.6      71.0         6.7             Rainy
4  2022-01-05      21.1         14.8      82.0         9.3             Rainy

## 🔧 Data Cleaning Operations on rainfall.csv

After uploading and loading the dataset, we perform:

---

### ✅ Operations:
1. Inspect data
2. Convert date column
3. Handle missing values
4. Fix text inconsistencies
5. Remove duplicates
6. Handle outliers
7. Feature engineering
8. Encoding categorical data
9. Save cleaned dataset

---

Each step is important for ML readiness.

In [ ]:
df.head()

df.info()

df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               54 non-null     object
 1   rainfall           53 non-null     float64
 2   temperature        53 non-null     float64
 3   humidity           53 non-null     float64
 4   wind_speed         53 non-null     float64
 5   weather_condition  53 non-null     object
dtypes: float64(4), object(2)
memory usage: 2.7+ KB

date                 0
rainfall             1
temperature          1
humidity             1
wind_speed           1
weather_condition    1
dtype: int64

## 🔹 Convert Date Column

Convert string → datetime format

---

Helps in:
- Sorting
- Time-based analysis

In [ ]:
df["date"] = df["date"].astype(str).str.strip()
df["date"] = pd.to_datetime(df["date"], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               53 non-null     datetime64[ns]
 1   rainfall           53 non-null     float64
 2   temperature        53 non-null     float64
 3   humidity           53 non-null     float64
 4   wind_speed         53 non-null     float64
 5   weather_condition  53 non-null     object
dtypes: datetime64[ns](1), float64(4), object(1)
memory usage: 2.7+ KB

## 🔹 Handle Missing Values

### Numerical Columns:
- rainfall
- temperature
- humidity
- wind_speed

➡️ Fill with mean

### Categorical:
- weather_condition

➡️ Fill with mode

In [ ]:
import pandas as pd

# Numerical columns
num_cols = ["rainfall", "temperature", "humidity", "wind_speed"]

# Fill numerical missing values with mean
df[num_cols] = df[num_cols].fillna(df[num_cols].mean())

# Fill categorical missing values with mode
df["weather_condition"] = df["weather_condition"].fillna(df["weather_condition"].mode()[0])

# Check missing values
print(df.isnull().sum())

date                 1
rainfall             0
temperature          0
humidity             0
wind_speed           0
weather_condition    0
dtype: int64

## 🔹 Fix Text Inconsistency

Standardize text:
- Rainy → rainy
- SUNNY → sunny

In [ ]:
df["weather_condition"] = df["weather_condition"].str.lower()

df["weather_condition"].unique()

df.head()

        date  rainfall  temperature  humidity  wind_speed weather_condition
0 2022-01-01      12.5         15.2      78.0         8.5             rainy
1 2022-01-02       8.2         17.8      65.0         5.2             rainy
2 2022-01-03       0.0         20.1      52.0         3.1             sunny
3 2022-01-04       3.7         18.6      71.0         6.7             rainy
4 2022-01-05      21.1         14.8      82.0         9.3             rainy

In [ ]:
df.to_csv("cleaned_rainfall.csv", index=False)

# Download
from google.colab import files#thisisamethodtodownloadfiles
files.download("cleaned_rainfall.csv")

In [ ]:
import pandas as pd
from google.colab import files

# Convert to Excel
df.to_excel("cleaned_rainfall.xlsx", index=False)

# Download
files.download("cleaned_rainfall.xlsx")

# 🎓 Student Performance Dataset – Data Cleaning

## 🎯 Objective:
Clean and preprocess student dataset for ML

---

## 🔹 Columns:
- name
- age
- gender
- marks
- attendance
- city

---

## ⚠️ Possible Issues:
- Missing values
- Inconsistent text (Male / male)
- Invalid marks (>100 or <0)
- Duplicates

In [ ]:

import pandas as pd
import numpy as np

data = {
    "name": ["Amit", "Sara", "John", "Amit", None],
    "age": [20, 21, np.nan, 20, 19],
    "gender": ["Male", "female", "Male", "Male", "FEMALE"],
    "marks": [85, 90, 105, 85, -5],
    "attendance": [90, 85, 80, 90, None],
    "city": ["Mumbai", "Delhi", "mumbai", "Mumbai", "Pune"]
}

df = pd.DataFrame(data)
df

   name   age  gender  marks  attendance    city
0  Amit  20.0    Male     85        90.0  Mumbai
1  Sara  21.0  female     90        85.0   Delhi
2  John   NaN    Male    105        80.0  mumbai
3  Amit  20.0    Male     85        90.0  Mumbai
4  None  19.0  FEMALE     -5         NaN    Pune

In [ ]:
df.info()
df.isnull().sum()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        4 non-null      object
 1   age         4 non-null      float64
 2   gender      5 non-null      object
 3   marks       5 non-null      int64
 4   attendance  4 non-null      float64
 5   city        5 non-null      object
dtypes: float64(2), int64(1), object(3)
memory usage: 372.0+ bytes

             age       marks  attendance
count   4.000000    5.000000    4.000000
mean   20.000000   72.000000   86.250000
std     0.816497   43.817805    4.787136
min    19.000000   -5.000000   80.000000
25%    19.750000   85.000000   83.750000
50%    20.000000   85.000000   87.500000
75%    20.250000   90.000000   90.000000
max    21.000000  105.000000   90.000000

## 🔹 Handling Missing Values

- age → mean
- attendance → mean
- name → "Unknown"

In [ ]:
df["age"].fillna(df["age"].mean(), inplace=True)
df["attendance"].fillna(df["attendance"].mean(), inplace=True)
df["name"].fillna("Unknown", inplace=True)

df

/tmp/ipykernel_1147/1440735091.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["age"].fillna(df["age"].mean(), inplace=True)
/tmp/ipykernel_1147/1440735091.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["attendance"].fillna(df["attendance"].mean(), inplace=True)
/tmp/ipykernel_1147/1440735091.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["name"].fillna("Unknown", inplace=True)

      name   age  gender  marks  attendance    city
0     Amit  20.0    Male     85       90.00  Mumbai
1     Sara  21.0  female     90       85.00   Delhi
2     John  20.0    Male    105       80.00  mumbai
3     Amit  20.0    Male     85       90.00  Mumbai
4  Unknown  19.0  FEMALE     -5       86.25    Pune

In [ ]:
df["gender"] = df["gender"].str.lower()
df["city"] = df["city"].str.lower()

df

      name   age  gender  marks  attendance    city
0     Amit  20.0    male     85       90.00  mumbai
1     Sara  21.0  female     90       85.00   delhi
2     John  20.0    male    105       80.00  mumbai
3     Amit  20.0    male     85       90.00  mumbai
4  Unknown  19.0  female     -5       86.25    pune

## 🔹 Fix Invalid Data

Marks should be:
- Between 0 and 100

In [ ]:
df = df[(df["marks"] >= 0) & (df["marks"] <= 100)]

df

   name   age  gender  marks  attendance    city
0  Amit  20.0    male     85        90.0  mumbai
1  Sara  21.0  female     90        85.0   delhi
3  Amit  20.0    male     85        90.0  mumbai

















## 🔹 Basic Questions

1. Load a CSV file and display:
   - First 5 rows
   - Last 5 rows

2. Find:
   - Total number of rows & columns
   - Data types of each column

3. Identify missing values:
   - Which columns have missing values?
   - Count them

4. Fill missing values:
   - Numerical → mean
   - Categorical → mode

5. Remove duplicate rows

6. Convert a column:
   - "date" → datetime format

7. Rename columns:
   - Change column names to lowercase

8. Change data type:
   - Convert float → int (where applicable)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df =  pd.read_csv('/content/data.csv')

In [ ]:
df.head()

,Student_ID,Name,Gender,Age,Department,Math_Marks,Science_Marks,English_Marks,Attendance_Percentage,Date_of_Birth,Admission_Date,Email
0,ST001,Aarav Sharma,Male,20,Computer Science,85,78.0,92,88,2006-05-14,2023-08-01,aarav.sharma@gmail.com
1,ST002,Priya Patel,Female,19,Computer Science,72,81.0,76,91,2007-02-21,2023-08-01,priya.patel@gmail.com
2,ST003,Rohan Kumar,Male,21,Information Technology,45,52.0,48,65,2005-11-10,2022-08-05,rohan.kumar@gmail.com
3,ST004,Sneha Joshi,Female,20,IT,91,88.0,94,96,2006-07-18,2023-08-01,sneha.joshi@gmail.com
4,ST005,Vikram Singh,Male,22,Computer Science,38,42.0,35,58,2004-03-25,2021-08-02,vikram.singh@gmail.com

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             20 non-null     object
 1   Name                   20 non-null     object
 2   Gender                 20 non-null     object
 3   Age                    20 non-null     int64
 4   Department             20 non-null     object
 5   Math_Marks             20 non-null     int64
 6   Science_Marks          19 non-null     float64
 7   English_Marks          20 non-null     int64
 8   Attendance_Percentage  20 non-null     int64
 9   Date_of_Birth          20 non-null     object
 10  Admission_Date         20 non-null     object
 11  Email                  20 non-null     object
dtypes: float64(1), int64(4), object(7)
memory usage: 2.0+ KB

In [ ]:
df.describe()

,Age,Math_Marks,Science_Marks,English_Marks,Attendance_Percentage
count,20.000000,20.000000,19.000000,20.000000,20.000000
mean,20.350000,70.000000,69.736842,71.100000,81.600000
std,1.089423,19.992104,18.119486,17.719748,12.575666
min,19.000000,29.000000,35.000000,35.000000,54.000000
25%,20.000000,57.250000,55.500000,59.500000,75.000000
50%,20.000000,71.500000,76.000000,74.000000,85.000000
75%,21.000000,85.750000,82.500000,85.250000,90.250000
max,23.000000,102.000000,97.000000,94.000000,98.000000

In [ ]:
df.isnull()

,Student_ID,Name,Gender,Age,Department,Math_Marks,Science_Marks,English_Marks,Attendance_Percentage,Date_of_Birth,Admission_Date,Email
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,True,False,False,False,False,False

In [ ]:
df.isnull().sum()

Student_ID               0
Name                     0
Gender                   0
Age                      0
Department               0
Math_Marks               0
Science_Marks            1
English_Marks            0
Attendance_Percentage    0
Date_of_Birth            0
Admission_Date           0
Email                    0
dtype: int64

In [ ]:
for col in df.columns:
    if df[col].dtype in ['int64', 'float64']:
        df[col] = df[col].fillna(df[col].mean())
    else:
        df[col] = df[col].fillna(df[col].mode()[0])

In [ ]:
df.isnull().sum()

Student_ID               0
Name                     0
Gender                   0
Age                      0
Department               0
Math_Marks               0
Science_Marks            0
English_Marks            0
Attendance_Percentage    0
Date_of_Birth            0
Admission_Date           0
Email                    0
dtype: int64

In [ ]:
initial_rows = len(df)
df = df.drop_duplicates()
print(f"Removed {initial_rows - len(df)} duplicate rows.")

Removed 0 duplicate rows.

In [ ]:
df['Date_of_Birth'] = pd.to_datetime(df['Date_of_Birth'], errors='coerce')
df['Admission_Date'] = pd.to_datetime(df['Admission_Date'], errors='coerce')

In [ ]:
df.columns = [col.lower() for col in df.columns]
print("Updated Column Names:", df.columns.tolist())

Updated Column Names: ['student_id', 'name', 'gender', 'age', 'department', 'math_marks', 'science_marks', 'english_marks', 'attendance_percentage', 'date_of_birth', 'admission_date', 'email']

In [ ]:
for col in df.columns:
    if df[col].dtype == 'float64':
        df[col] = df[col].astype(int)

print("\nFinal Data Types:\n", df.dtypes)

Final Data Types:
 student_id                       object
name                             object
gender                           object
age                               int64
department                       object
math_marks                        int64
science_marks                     int64
english_marks                     int64
attendance_percentage             int64
date_of_birth            datetime64[ns]
admission_date           datetime64[ns]
email                            object
dtype: object

## 🔹 Intermediate Questions

1. Select multiple columns and:
   - Fill missing values together

2. Apply transformation:
   - Increase salary/marks by 10%

3. Fix inconsistent text:
   - "Mumbai", "mumbai", "MUMBAI" → one format

4. Create new column:
   - Example: "Pass/Fail" based on marks

5. Filter data:
   - Students with marks > 80
   - Rainfall > 10

6. Drop unnecessary columns:
   - Based on relevance

7. Apply One-Hot Encoding:
   - On categorical columns

8. Sort dataset:
   - Based on date or marks

In [ ]:
import pandas as pd

df = pd.read_csv('data.csv')

# Select multiple specific columns and fill their missing values with 0 (or their respective mean)
cols_to_fill = ['Math_Marks', 'Science_Marks', 'English_Marks']
df[cols_to_fill] = df[cols_to_fill].fillna(df[cols_to_fill].mean())

In [ ]:
# Increase math marks by 10%
df['Math_Marks'] = df['Math_Marks'] * 1.10

In [ ]:
# Convert to title case to fix capitalization mismatches
df['Department'] = df['Department'].str.title()

# Fix variations like 'It' to 'Information Technology' if needed
df['Department'] = df['Department'].replace({'It': 'Information Technology'})

In [ ]:
# Calculate average marks across subjects
df['Average_Marks'] = df[['Math_Marks', 'Science_Marks', 'English_Marks']].mean(axis=1)

# Assign Pass if average >= 50, else Fail
df['Pass_Fail'] = df['Average_Marks'].apply(lambda x: 'Pass' if x >= 50 else 'Fail')

In [ ]:
# Filter students with Math marks greater than 80
high_math_scorers = df[df['Math_Marks'] > 80]

# Example for rainfall (if rainfall column exists in another dataset):
# high_rainfall = df[df['Rainfall'] > 10]

In [ ]:
# Drop the 'Email' column
df = df.drop(columns=['Email'])

In [ ]:
# Apply one-hot encoding on categorical columns like Gender and Department
df_encoded = pd.get_dummies(df, columns=['Gender', 'Department'])

In [ ]:
# Sort dataset by Math Marks in descending order (highest first)
df_sorted = df.sort_values(by='Math_Marks', ascending=False)

# Or sort by date
# df_sorted_date = df.sort_values(by='Admission_Date', ascending=True)